export const currencies = [
  { code: "USD", name: "US Dollar", flag: "🇺🇸" },
  { code: "EUR", name: "Euro", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", flag: "🇬🇧" },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵" },
  { code: "AUD", name: "Australian Dollar", flag: "🇦🇺" },
  { code: "CAD", name: "Canadian Dollar", flag: "🇨🇦" },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭" },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰" },
  { code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿" },
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪" },
  { code: "KRW", name: "South Korean Won", flag: "🇰🇷" },
  { code: "SGD", name: "Singapore Dollar", flag: "🇸🇬" },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴" },
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽" },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳" },
  { code: "RUB", name: "Russian Ruble", flag: "🇷🇺" },
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦" },
  { code: "TRY", name: "Turkish Lira", flag: "🇹🇷" },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷" },
  { code: "TWD", name: "Taiwan Dollar", flag: "🇹🇼" },
  { code: "DKK", name: "Danish Krone", flag: "🇩🇰" },
  { code: "PLN", name: "Polish Zloty", flag: "🇵🇱" },
  { code: "THB", name: "Thai Baht", flag: "🇹🇭" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩" },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺" },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿" },
  { code: "ILS", name: "Israeli Shekel", flag: "🇮🇱" },
  { code: "CLP", name: "Chilean Peso", flag: "🇨🇱" },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭" },
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪" },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴" },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾" },
  { code: "RON", name: "Romanian Leu", flag: "🇷🇴" },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬" },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷" },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬" },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳" },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦" },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪" },
  { code: "PEN", name: "Peruvian Sol", flag: "🇵🇪" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭" },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦" },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼" },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭" },
  { code: "OMR", name: "Omani Rial", flag: "🇴🇲" },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰" },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿" },
  { code: "ZMW", name: "Zambian Kwacha", flag: "🇿🇲" },
  { code: "RWF", name: "Rwandan Franc", flag: "🇷🇼" },
];

export const cryptoCurrencies = [
  { code: "BTC", name: "Bitcoin" },
  { code: "ETH", name: "Ethereum" },
  { code: "USDT", name: "Tether" },
  { code: "USDC", name: "USD Coin" },
  { code: "BNB", name: "Binance Coin" },
  { code: "TRX", name: "Tron" },
  { code: "SOL", name: "Solana" },
  { code: "XRP", name: "Ripple" },
  { code: "ADA", name: "Cardano" },
  { code: "DOT", name: "Polkadot" },
  { code: "DOGE", name: "Dogecoin" },
  { code: "AVAX", name: "Avalanche" },
  { code: "LINK", name: "Chainlink" },
  { code: "LTC", name: "Litecoin" },
  { code: "ATOM", name: "Cosmos" },
  { code: "XLM", name: "Stellar" },
  { code: "ETC", name: "Ethereum Classic" },
  { code: "ZEC", name: "Zcash" },
  { code: "DASH", name: "Dash" },
  { code: "XTZ", name: "Tezos" },
];
