kind = "web"
previewPath = "/"
title = "Pexly"
version = "1.0.0"
id = "artifacts/pexly"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22278

[services.development]
run = "pnpm --filter @workspace/pexly run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/pexly", "run", "build" ]
publicDir = "artifacts/pexly/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22278"
BASE_PATH = "/"
